@IsTest
public with sharing class TestConstants {
    public static final String NOT_STARTED_MONITORING_STATUS = 'Not Started';
    public static final String SOME_CATEGORY_LEAD_INDUSTRY = 'Some Category';

    public static final String FRANCE_COUNTRY_NAME = 'France';
    public static final String FRANCE_COUNTRY_CODE = 'FR';
    public static final String US_COUNTRY_NAME = 'United States';
    public static final String US_COUNTRY_CODE = 'US';
    public static final Integer US_VISITS = 100;
    public static final Integer FRANCE_VISITS = 150;

    public static final String TEST_NAME = 'Test Name';
    public static final String TEST_STAGE = 'Meeting';
    public static final String TEST_NEGOTIATION_STAGE = 'Negotiation';
    public static final String TEST_COMMENT = 'Test Comment';
    public static final String TEST_NEW_COMMENT = 'Test New Comment';
    public static final String SYSTEM_ADMINISTRATOR = 'System Administrator';
    public static final String AML_TOOL_VERSION = 'v 1';
    public static final String TEST_SITE_URL = 'example.com';
    public static final String TEST_EMAIL = 'test@example.com';
    public static final String TEST_WEBSITE = 'site.com';
    public static final String TEST_SEARCH_KEY = 'search key';
    public static final String TEST_OBJECT = 'Object';
    public static final String TEST_FIELD = 'Field';
    public static final String TEST_PRODUCT = 'Product__c';

    public static final String JIRA_EXTERNAL_ID = '1234';

    public static final Integer NEW_RECORDS = 200;

    public static final String NODA_CS_DOMAINS_BLACK_LIST = 'company.com, example.com, test.com, google.com, facebook.com, instagram.com';
    public static final String NODA_CS_ORG_URL = 'noda.sandbox.lightning.force.com/';
    public static final String NODA_CS_JIRA_API_TOKEN = 'TATT3xFfGF0kbV';
    public static final String NODA_CS_JIRA_PROJECT_KEY = 'SNS';
    public static final String NODA_CS_JIRA_URL = 'https://nodapay.atlassian.net';
    public static final String NODA_CS_JIRA_USERNAME = 'test@test.test';
    public static final String NODA_CS_STANDARD_OPPORTUNITY = 'Legal,Onboarding,Merchant approve';
    public static final String NODA_CS_UP_SALE_OPPORTUNITY = 'Noda Go,Noda Buffet,Pay In,Pay Out,Payment links';

    public static final String POST = 'POST';
    public static final String GET = 'GET';
    public static final String CONTENT_TYPE = 'Content-Type';
    public static final String APPLICATION_JSON = 'application/json';
    public static final String AUTHORIZATION = 'Authorization';
    public static final String BASIC = 'Basic ';

    public static final String SLACK_BOT_TOKEN = 'test_token';
    public static final String SLACK_CHANNEL_NAME = 'test_channel_Name';
    public static final String DIGITAL_SLACK_CHANNEL_NAME = 'test_digital_Name';

    public static final String USER_TYPE_STANDARD = 'Standard';

    public static final String INTEGRATION_KEY = 'key';

    public static final String TEMPLATE_DEVELOPER_NAME = 'Test_Template';
}